# Numpy

- An array is a data structure that stores values for same data type.

In [7]:
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
my_list = [1,2,3,4,5,6,7]
my_list

[1, 2, 3, 4, 5, 6, 7]

In [3]:
ar1 = np.array(my_list)
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
ar1.shape

(7,)

As this is a 1 dimensional array.

In [11]:
my_list1 = [17,18,19,37,67,89,77]
my_list2 = [78, 77, 890, 87, 67, 78, 89]

ar2 = np.array([my_list,my_list1,my_list2])
ar2

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 17,  18,  19,  37,  67,  89,  77],
       [ 78,  77, 890,  87,  67,  78,  89]])

In [14]:
# trying to retrive 19,37,890,87 in ar2
ar2[1:,2:4]

array([[ 19,  37],
       [890,  87]])

In [17]:
ar3=np.arange(1,15, step= 3)
ar3

array([ 1,  4,  7, 10, 13])

In [18]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
#copy function & broadcasting
#- it changes the elements to teh desired value from index positions
ar3[2:]=100
ar3

array([  1,   4, 100, 100, 100])

In [20]:
ar4 = ar3
ar4[1:]=500
ar4

array([  1, 500, 500, 500, 500])

In [21]:
ar3

array([  1, 500, 500, 500, 500])

Arrays are reference type structures , where teh value gets updated from new variable to old variable.

To prevent this to happen, we use copy() to reate another memory space where it stores the array information.

In [22]:
ar3_copy = ar3.copy()
ar3[1:] = 1234

In [23]:
print(ar3_copy)
print(ar3)

[  1 500 500 500 500]
[   1 1234 1234 1234 1234]


In [24]:
ar3<1000

array([ True, False, False, False, False])

All mathematical operatins gets applied to all the elements.

## Pandas

In [26]:
import pandas as pd
import numpy as np

In [33]:
df=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['Row1','Row2','Row3','Row4'],columns = ['column1', 'column2', 'column3', 'column4', 'column5'])
df

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

.loc is location of the row. - used to retreive a single row.

.iloc is location of the rows & columns - used for retreiving a smaller dataframe out of the bigger one.

- dataframe is a combination of many columns & many rows( atleast >1 row & >1 column)
- data series can have only 1 row & only 1 column as well.

- 1 row many columns : Series
- many series : a dataframe

In [36]:
df.loc['Row2']

column1    5
column2    6
column3    7
column4    8
column5    9
Name: Row2, dtype: int32

In [37]:
type(df.loc['Row2'])

pandas.core.series.Series

In [43]:
df.iloc[1:3,2:4]

column3  column4
Row2        7        8
Row3       12       13

In [50]:
df.iloc[0:3,1]

Row1     1
Row2     6
Row3    11
Name: column2, dtype: int32

In [51]:
type(df.iloc[0:3,1])

pandas.core.series.Series

In [52]:
df.iloc[0:3,1:4]

column2  column3  column4
Row1        1        2        3
Row2        6        7        8
Row3       11       12       13

In [53]:
type(df.iloc[0:3,1:4])

pandas.core.frame.DataFrame

if i dont give more than 1 columns in iloc, it considers the datatype as series.

## Dataframe into array

In [55]:
df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [56]:
type(df.iloc[:,1:].values)

numpy.ndarray

- using .values into df- we can modify the type into numpy array

In [57]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
column5    0
dtype: int64

In [58]:
df.head()

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [62]:
df['column2'].value_counts()

column2
1     1
6     1
11    1
16    1
Name: count, dtype: int64

.value_counts() is used to get the frewuency of teh values in the column - useful in categorical variables.

Accessing the column values for each row - we can directly use the df['columnname'] or df[['column1_name','column2_name']] in case we want multiple column info.

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  4 non-null      int32
 1   column2  4 non-null      int32
 2   column3  4 non-null      int32
 3   column4  4 non-null      int32
 4   column5  4 non-null      int32
dtypes: int32(5)
memory usage: 284.0+ bytes


In [68]:
df.describe()

column1    column2    column3    column4    column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

.describe() gives us the stats of columns of numerical variables. doesnt work on categorical one.

In [76]:
from io import StringIO, BytesIO

data= ('col1,col2,col3\n'
           'x,y,z\n'
           'a,b,c')


In [79]:
pd.read_csv(StringIO(data))

col1 col2 col3
0    x    y    z
1    a    b    c

We can use StringIO to create a df from string format

In [83]:
#Read from specific columns
df=pd.read_csv(StringIO(data), usecols=['col1','col2'])
df

col1 col2
0    x    y
1    a    b

In [100]:
data1= ('col1,col2,col3,col4\n'
           '1,2,3,4\n'
           '8,7,6,5\n'
           '9,10,11,12')
df1= pd.read_csv(StringIO(data1),dtype=object)
df1

col1 col2 col3 col4
0    1    2    3    4
1    8    7    6    5
2    9   10   11   12

In [101]:
df1['col1']

0    1
1    8
2    9
Name: col1, dtype: object

In [102]:
df1['col2'][2]

'10'

This gives me a string format valueas i had converted teh vaues to object while reading this.

In [103]:
df2= pd.read_csv(StringIO(data1))
df2

col1  col2  col3  col4
0     1     2     3     4
1     8     7     6     5
2     9    10    11    12

In [104]:
df2['col1']

0    1
1    8
2    9
Name: col1, dtype: int64

In [105]:
df2['col2'][1]

7

When we dont use the dtype in the read syntax, it by default takes the type of value.

In [112]:
data2= ('col1,col2,col3,col4\n'
           'x,2,3,4\n'
           '8,7,6,5\n'
           '9,y,11,12')

In [113]:
df3= pd.read_csv(StringIO(data2))
df3

col1 col2  col3  col4
0    x    2     3     4
1    8    7     6     5
2    9    y    11    12

In [116]:
df3['col1']

0    x
1    8
2    9
Name: col1, dtype: object

If one element is of string format, it assigns all itmes as string.

In [117]:
df3['col3']

0     3
1     6
2    11
Name: col3, dtype: int64

If the column has all same data type, it wll assign the datatype of column as that or else 'string'.

In [125]:
df4 = pd.read_csv(StringIO(data2),dtype={'col1':object, 'col2':str, 'col3':float, 'col4':'int64'})
df4

col1 col2  col3  col4
0    x    2   3.0     4
1    8    7   6.0     5
2    9    y  11.0    12

In [126]:
df4.dtypes

col1     object
col2     object
col3    float64
col4      int64
dtype: object

So, we can read the file with predefined datatypes for columns.

In [129]:
data3 = ('index,col1,col2,col3\n'
           '1,red,3,4\n'
           '8,7,blue,5\n'
           '9,10,11,lion')
df5 = pd.read_csv(StringIO(data3),index_col=0)
df5

col1  col2  col3
index                 
1      red     3     4
8        7  blue     5
9       10    11  lion

In [130]:
df5 = pd.read_csv(StringIO(data3),index_col=2)
df5

index col1  col3
col2                  
3         1  red     4
blue      8    7     5
11        9   10  lion

In [132]:
df5 = pd.read_csv(StringIO(data3),index_col=False)
df5

index col1  col2  col3
0      1  red     3     4
1      8    7  blue     5
2      9   10    11  lion

We can define our index column here with the column index as 'index_col=' in pd.read_csv which will assign the specified column as index for df instead of creating another index.

In [133]:
# Quoting & escape character - ISEFUL IN NLP!!!

data = 'a,b,c\n"Hello, \\"Priyaranjan\\", How are you",5'

In [134]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b   c
0  Hello, "Priyaranjan", How are you  5 NaN

In [142]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header = None)
df

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [165]:
Data ='[{"name":"Ram", "email":"Ram@gmail.com"}, {"name":"Bob", "email":"bob32@gmail.com"}]' 
df_data = pd.read_json(Data)
df_data

name            email
0  Ram    Ram@gmail.com
1  Bob  bob32@gmail.com

In [173]:
df_data.to_json(orient='records')

'[{"name":"Ram","email":"Ram@gmail.com"},{"name":"Bob","email":"bob32@gmail.com"}]'

Converting the df to json format.
- orient = 'index' will give me dictionary of key- index/row value & value- row
- orient = 'records' will give me the row information sequentially row wise without the index value.

In [159]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

json : list of dictionaries, we can read them using pd.read_json()..

In [175]:
url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url, match = 'Mobile country code', header = 0)

In [176]:
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]